// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @title InvoiceNFT
 * @notice Tokenizes verified invoice financing assets for Invoice2Credit AI.
 * @dev Inherits ERC721URIStorage and AccessControl from OpenZeppelin.
 * Privacy-preserving: Stores only a SHA-256 fingerprint (bytes32) of the invoice,
 * a non-sensitive public reference string, and basic payment terms.
 */
contract InvoiceNFT is ERC721URIStorage, AccessControl {
    // Custom roles
    bytes32 public constant VERIFIER_ROLE = keccak256("VERIFIER_ROLE");
    bytes32 public constant MARKETPLACE_ROLE = keccak256("MARKETPLACE_ROLE");

    // Token ID tracker
    uint256 private _nextTokenId;

    struct InvoiceRecord {
        uint256 tokenId;
        bytes32 invoiceHash;
        string invoiceReference;
        uint256 invoiceAmount;
        uint256 dueDate;
        address msme;
        address buyer; // Assigned corporate buyer responsible for paying the invoice
        bool verified;
        uint256 mintedAt;
    }

    // Mapping from token ID to invoice record
    mapping(uint256 => InvoiceRecord) public invoiceRecords;

    // Mapping to prevent double financing / duplicate tokenization of the same invoice document
    mapping(bytes32 => bool) public usedInvoiceHashes;

    // Mapping to prevent refinancing of an already-financed NFT
    mapping(uint256 => bool) public financedTokens;

    // Custom errors
    error InvoiceHashAlreadyUsed(bytes32 invoiceHash);
    error InvalidInvoiceHash();
    error InvalidAmount();
    error InvalidDueDate();
    error ZeroAddress();
    error TokenAlreadyFinanced(uint256 tokenId);
    error OnlyMarketplace();
    error TokenDoesNotExist();

    // Events
    event InvoiceMinted(
        uint256 indexed tokenId,
        bytes32 indexed invoiceHash,
        address indexed msme,
        address buyer,
        string invoiceReference,
        uint256 invoiceAmount,
        uint256 dueDate,
        uint256 mintedAt
    );
    event TokenMarkedAsFinanced(uint256 indexed tokenId);

    constructor() ERC721("Invoice2Credit NFT", "I2CNFT") {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(VERIFIER_ROLE, msg.sender);
        _nextTokenId = 1;
    }

    /**
     * @notice Mints a new invoice NFT representing a verified invoice.
     * @dev Only callable by accounts holding VERIFIER_ROLE.
     * @param msme The address of the MSME requesting financing (receives the NFT).
     * @param buyer The address of the corporate buyer responsible for paying the invoice.
     * @param invoiceHash The SHA-256 fingerprint generated by the AI backend.
     * @param invoiceReference A unique non-sensitive public reference string.
     * @param invoiceAmount The amount of the invoice in native token units.
     * @param dueDate The block timestamp representing the payment due date.
     * @param tokenURI The IPFS URI referencing the non-sensitive metadata details.
     * @return The newly minted tokenId.
     */
    function mintInvoice(
        address msme,
        address buyer,
        bytes32 invoiceHash,
        string calldata invoiceReference,
        uint256 invoiceAmount,
        uint256 dueDate,
        string calldata tokenURI
    ) external onlyRole(VERIFIER_ROLE) returns (uint256) {
        if (msme == address(0) || buyer == address(0)) revert ZeroAddress();
        if (invoiceHash == bytes32(0)) revert InvalidInvoiceHash();
        if (usedInvoiceHashes[invoiceHash]) revert InvoiceHashAlreadyUsed(invoiceHash);
        if (invoiceAmount == 0) revert InvalidAmount();
        if (dueDate <= block.timestamp) revert InvalidDueDate();

        uint256 tokenId = _nextTokenId;
        _nextTokenId++;

        // Mint ERC721 token to MSME
        _safeMint(msme, tokenId);
        _setTokenURI(tokenId, tokenURI);

        // Record the invoice data on-chain
        invoiceRecords[tokenId] = InvoiceRecord({
            tokenId: tokenId,
            invoiceHash: invoiceHash,
            invoiceReference: invoiceReference,
            invoiceAmount: invoiceAmount,
            dueDate: dueDate,
            msme: msme,
            buyer: buyer,
            verified: true,
            mintedAt: block.timestamp
        });

        // Mark the SHA-256 fingerprint as used to prevent duplicate listing
        usedInvoiceHashes[invoiceHash] = true;

        emit InvoiceMinted(
            tokenId,
            invoiceHash,
            msme,
            buyer,
            invoiceReference,
            invoiceAmount,
            dueDate,
            block.timestamp
        );

        return tokenId;
    }

    /**
     * @notice Marks a token as financed. Called only by authorized marketplaces.
     * @param tokenId The token ID of the invoice NFT.
     */
    function markAsFinanced(uint256 tokenId) external onlyRole(MARKETPLACE_ROLE) {
        // Ensure token exists (checked via ownerOf)
        try this.ownerOf(tokenId) returns (address) {
            // Token exists
        } catch {
            revert TokenDoesNotExist();
        }

        if (financedTokens[tokenId]) revert TokenAlreadyFinanced(tokenId);
        financedTokens[tokenId] = true;

        emit TokenMarkedAsFinanced(tokenId);
    }

    /**
     * @dev Overrides supportInterface to handle multiple inheritances.
     */
    function supportsInterface(bytes4 interfaceId)
        public
        view
        override(ERC721URIStorage, AccessControl)
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }
}
